services:
  - type: web
    name: laravel-app
    env: php
    plan: starter
    
    buildCommand: |
      composer install --optimize-autoloader --no-dev && \
      npm ci --omit=dev && \
      npm run build && \
      php artisan storage:link && \
      php artisan config:cache && \
      php artisan route:cache
    
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: VITE_PUSHER_APP_KEY
        value: "457bad3e2d611af861ed"
      - key: VITE_PUSHER_APP_CLUSTER
        value: "ap1"

  - type: pserv
    name: laravel-postgres
    plan: starter
    ipAllowList: []
    postgresDatabaseName: render_db
    postgresDatabaseUser: render_user